version: '2'
services:
  es-dev-1:
    image: jaysong/elasticsearch:5.4.0
    container_name: es-dev-1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - ./esconf1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./esconf1/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - esdata1:/var/data/elasticsearch
      - eslog1:/var/log/elasticsearch
    ports:
      - 9200:9200
    networks:
      - esnet
  es-dev-2:
    image: jaysong/elasticsearch:5.4.0
    container_name: es-dev-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - ./esconf2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./esconf2/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - esdata2:/var/data/elasticsearch
      - eslog2:/var/log/elasticsearch
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  eslog1:
    driver: local
  eslog2:
    driver: local

networks:
  esnet:
    driver: bridge
